version: 2.1

jobs:
  Add-to-doc:
    docker:
      - image: circleci/node:13.8.0
    steps:
      #- checkout
      - run:
          name: Add back-end ip to ansible inventory
          command: |
            # Your code here
            echo "1234" > inventory.txt
            cat inventory.txt
      - run:
          name: Add more contents to txt
          command: |
            echo "qwer" >> inventory.txt
      - run:
          name: Check the contents of inventory.txt
          command: cat inventory.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - project/inventory.txt

  Check-workspace:
    docker:
      - image: circleci/node:13.8.0
    steps:
      #- checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Check workspace path and contents
          command: |
            echo "pwd"
            pwd                    # The result is /root/project
            # cd ..
            ls
            echo "inventory.txt"
            cat inventory.txt # -> There isn't /root/project/inventory.txt
            ls
            echo "~/project/inventory.txt"
            cat ~/project/inventory.txt # -> ~/ means /root/. And there isn't /root/project/inventory.txt
            #echo "~/project/.circleci/inventory.txt"
            #cat ~/project/.circleci/inventory.txt
            echo "ls"
            ls

workflows:
  default:
    jobs:
      - Add-to-doc
      - Check-workspace:
          requires:
            - Add-to-doc      
          